# Generated by Django 4.2.3 on 2023-08-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_postal_code',
            field=models.IntegerField(null=True, verbose_name=range(10000, 99999)),
        ),
        migrations.DeleteModel(
            name='UserDefaultInfo',
        ),
    ]
