# Generated by Django 4.2.1 on 2023-06-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='default_country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription',
        ),
        migrations.AddField(
            model_name='profile',
            name='default_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_postal_code',
            field=models.IntegerField(default=0, verbose_name=range(10000, 99999)),
        ),
    ]
