# Generated by Django 4.2.1 on 2023-06-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_default_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_postal_code',
            field=models.IntegerField(verbose_name=range(10000, 99999)),
        ),
    ]
