# Generated by Django 4.2.1 on 2023-06-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_default_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='no image found', upload_to=None),
        ),
    ]
