# Generated by Django 4.2.1 on 2023-06-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_postal_code',
            field=models.IntegerField(null=True, verbose_name=range(10000, 99999)),
        ),
    ]
