# Generated by Django 4.2.1 on 2023-05-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcription',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subcription',
            name='included_products',
        ),
        migrations.AddField(
            model_name='subcription',
            name='billing_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subcription',
            name='name',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
