# Generated by Django 4.2.1 on 2023-05-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscription_delete_subcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
