# Generated by Django 4.2.1 on 2023-06-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subscription_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='name',
            new_name='subscription_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
