# Generated by Django 4.2.1 on 2023-06-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_subscription_stripe_subscription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='billing_address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='subscription',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='postal_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
