# Generated by Django 4.2.1 on 2023-06-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_rename_billing_address_subscription_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='postal_code',
            field=models.IntegerField(default=0, verbose_name=range(10000, 99999)),
        ),
    ]
