# Generated by Django 4.2.1 on 2023-06-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_alter_subscription_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='postal_code',
            field=models.IntegerField(verbose_name=range(10000, 99999)),
        ),
    ]
