# Generated by Django 4.2.3 on 2023-07-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='milk_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='size',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
