# Generated by Django 4.2.1 on 2023-05-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.TextField(default=''),
        ),
    ]
