# Generated by Django 4.2.3 on 2023-07-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderlineitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='to_go',
            field=models.BooleanField(default=True),
        ),
    ]
