# Generated by Django 4.2.1 on 2023-05-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_cart_orderlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.product'),
        ),
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
    ]
