# Generated by Django 4.2.1 on 2023-05-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
