# Generated by Django 4.2.1 on 2023-06-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
    ]
