# Generated by Django 4.2.1 on 2023-06-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_remove_order_city_remove_order_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
