# Generated by Django 4.2.3 on 2023-07-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_additions_product_description_product_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
