# Generated by Django 4.2.3 on 2023-07-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_milk',
            field=models.BooleanField(default=True),
        ),
    ]
